### ISSUE TITLE
Add Sponser Section

### ISSUE THREAD

**Issue by xaviertintin** [HultPrize/landing-page#1]
- [x] Add host (EPN)
- [x] Add Cohost
> - Faculties: FIS, FCA
> - Clubs: NOVA, Entrepreneurship

- [x] Externals
> - Sponsers: Chaskis, WORB
> - Media Partners: ?
> - Strategic Alies: CEDIA, ?

Data will be provided by @padimaster

**Comment by padimaster** [comment]
# Sponsor Content
```typescript
type Sponsor = {
  name: string;
  logo: {
    url: string;
    size: {
      width: number;
      height: number;
    };
  };
  url: string;
};
```
This TypeScript code defines a Sponsor type, which includes the name of the sponsor, a logo object containing the url of the logo image and its size (width and height), and a url for the sponsor's website.

# Logo Size Standards


```typescript
const logoSizes = {
  square: {
    width: 125,
    height: 125,
  },
  horizontal: {
    width: 250,
    height: 125,
  },
  vertical: {
    width: 125,
    height: 250,
  },
};
```
Here, is defined a constant logoSizes that provides standard width and height values for different types of logos: square, horizontal, and vertical.

To relate these code snippets to the issue of adding a Sponsor Section:

- The Sponsor type provides a structured representation for the content of each sponsor, including their name, logo details, and website URL.
- The logoSizes constant establishes standard dimensions for different types of logos, ensuring consistency in the Sponsor Section.

**Comment by padimaster** [comment]
# Sponsor Section Content
Sponsors data is available at **src/lib/sponsors.lib.ts**

<img width="296" alt="image" src="https://github.com/HultPrize/landing-page/assets/71728367/9290a9ac-26a2-41b3-b75a-6849ef58e285">

**Comment by padimaster** [comment]
# Sponsors Images:

## Host
EPN: [logo](https://hult-prize.s3.amazonaws.com/university/epn.png)

## Co-Hosts
FIS: [logo](https://hult-prize.s3.amazonaws.com/university/fis.png)
FCA: 

## Sponsors
Nova: [logo](https://hult-prize.s3.amazonaws.com/university/full.png)
Club de Emprendimiento: [logo](https://hult-prize.s3.amazonaws.com/university/Propuesta+Logo+Club+Emprendimiento+EPN+wb+(1).png)

## Strategic Allies
Imagen Sistemas: [logo](https://hult-prize.s3.amazonaws.com/university/imagen-sistemas.png)

**Comment by padimaster** [comment]
# S3 Bucket
I created a S3 Bucket with the following content:
<img width="438" alt="image" src="https://github.com/HultPrize/landing-page/assets/71728367/12ebd0b8-efdb-409b-98e8-eab0ae575d79">

For the moment, all Sponsors Section logos are in **university folder**
<img width="247" alt="image" src="https://github.com/HultPrize/landing-page/assets/71728367/166535ef-e3df-4c1c-9a7f-8441d5b6eb06">


For public access, I also added the following bucket policy:
<img width="404" alt="image" src="https://github.com/HultPrize/landing-page/assets/71728367/d810f425-4d61-48d5-9e8c-ab69c4d5f7f8">

**Comment by Ricker2020** [comment]
Things that are missing
- [ ] FCA image
- [ ] Externals

by @padimaster

**Comment by padimaster** [comment]
Updated data:

FCA: [logo](https://hult-prize.s3.amazonaws.com/university/fca.png)

Externals
Chaskis: [logo](https://hult-prize.s3.amazonaws.com/sponsors/chaskis.svg)

**Comment by Ricker2020** [comment]
Finished
