### ISSUE TITLE
Integrate application forms

### ISSUE THREAD

**Issue by padimaster** [HultPrize/landing-page#12]
Forms link will be provided by @xaviertintin

**Comment by padimaster** [comment]
# Application Forms
- [Interested](https://docs.google.com/forms/d/1Z6dONjv-cC3Zgzbc92Eelrb6g0rr4o7Xq7RvIXEKGhM/edit?usp=drivesdk)
- [Teams](https://docs.google.com/forms/d/1WOS9JftYT_AgrGiOc4h1lQy6rKa_B7Ifi-XnUXVksao/edit?usp=drivesdk)

**Comment by Ricker2020** [comment]
Can you put the form embed codes?
by @padimaster
